workflows:
  ios-release:
    name: Flutter iOS TestFlight Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    integrations:
      app_store_connect: AppStoreKey
      
    # Codemagic will now automatically log in, fetch the profiles we created earlier, 
    # and generate the export options file for you.
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ruby: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pang2chocolate.app
        
    scripts:
      - name: Install dependencies
        script: |
          flutter config --no-enable-swift-package-manager
          flutter pub get
          cd ios && pod install
          
      - name: Apply Profiles to Xcode
        script: |
          # This injects the downloaded certificates into your now-unlocked project file
          xcode-project use-profiles
          
      - name: Build IPA
        script: |
          # Flutter builds the app using the certificates Codemagic prepared
          flutter build ipa --release --export-options-plist=$CM_EXPORT_OPTIONS
          
    artifacts:
      - build/ios/ipa/*.ipa
      - ~/.fastlane/logs/**/*.log
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true