org.gradle.jvmargs=-Xmx4096m
org.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=true
android.enableBuildScaling=false
kotlin.incremental=true
kotlin.incremental.multiplatform=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
